/**
 * Domain types for Centsible.
 *
 * Money is always stored as an integer number of cents (minor currency
 * units). This sidesteps floating point drift entirely — 0.1 + 0.2 !== 0.3
 * in IEEE-754, and a budgeting tool is exactly the wrong place to find that
 * out. `amountCents: 1050` means $10.50. Conversion only ever happens at
 * the input/output boundary (see `domain/money.ts`).
 */

export type TransactionType = 'income' | 'expense';

export type CategoryKind = TransactionType | 'both';

export interface Category {
  id: string;
  name: string;
  /** Hex color used for chart segments, dots, and left-accent bars. */
  color: string;
  /** lucide-react icon name, e.g. "shopping-cart". */
  icon: string;
  kind: CategoryKind;
  /** Built-in categories ship with the app; user categories can be deleted. */
  isDefault?: boolean;
}

export interface Transaction {
  id: string;
  type: TransactionType;
  amountCents: number;
  categoryId: string;
  description: string;
  /** ISO date, YYYY-MM-DD (no time component — a transaction happens "on" a day). */
  date: string;
  notes?: string;
  /** Present when this transaction was generated by a recurring rule. */
  recurringRuleId?: string;
  createdAt: string;
  updatedAt: string;
}

export type RecurrenceFrequency = 'daily' | 'weekly' | 'monthly' | 'yearly';

export interface RecurringRule {
  id: string;
  type: TransactionType;
  amountCents: number;
  categoryId: string;
  description: string;
  frequency: RecurrenceFrequency;
  /** Repeat every N units of `frequency` — "every 2 weeks", "every 3 months". */
  interval: number;
  startDate: string;
  /** Omit for a rule that repeats indefinitely. */
  endDate?: string;
  /**
   * The latest date up to which real Transaction rows have already been
   * materialized for this rule, so the engine never double-books an
   * occurrence. Advances forward as the app runs.
   */
  lastMaterializedDate?: string;
  isPaused?: boolean;
}

export interface Budget {
  id: string;
  categoryId: string;
  monthlyLimitCents: number;
}

export type ThemeMode = 'light' | 'dark';

export interface Settings {
  currency: string; // ISO 4217, e.g. "USD"
  locale: string; // BCP 47, e.g. "en-US"
  theme: ThemeMode;
}

export interface AppState {
  transactions: Transaction[];
  categories: Category[];
  recurringRules: RecurringRule[];
  budgets: Budget[];
  settings: Settings;
}

/** Discriminated status used for budget progress bars and dashboard alerts. */
export type BudgetStatus = 'under' | 'warning' | 'over';

export interface BudgetProgress {
  budgetId: string;
  categoryId: string;
  limitCents: number;
  spentCents: number;
  remainingCents: number;
  percentUsed: number;
  projectedEndOfMonthCents: number;
  status: BudgetStatus;
}

export interface CategoryTotal {
  categoryId: string;
  totalCents: number;
  percentOfTotal: number;
}

export interface MonthlyTotal {
  /** YYYY-MM */
  month: string;
  incomeCents: number;
  expenseCents: number;
}

export interface UpcomingOccurrence {
  ruleId: string;
  date: string;
  type: TransactionType;
  amountCents: number;
  categoryId: string;
  description: string;
}

export interface ToastMessage {
  id: string;
  text: string;
  tone: 'default' | 'success' | 'danger';
  /** Optional inline action, e.g. "Undo". */
  actionLabel?: string;
  onAction?: () => void;
}
